### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by wolf943134497** [Grandzxw/MMF-LVINS#2]
@Grandzxw  Thanks for your great works!
Will all the MMF-LVINS system code be open source? or just the loop closure module code. thanks

**Comment by Grandzxw** [comment]
> @Grandzxw Thanks for your great works! Will all the MMF-LVINS system code be open source? or just the loop closure module code. thanks

Thank you for your attention. we have no plans to open source all the code for the time being, and we will let you know about it in the future.
